salt with hash size
esrp/ruby pull request #1
Opened 2018-02-26 15:50 UTC by nsheremet

2018-02-27 13:38 UTC, Ptico commented on spec/unit/crypto/openssl_spec.rb
> +  # frozen_string_literal: true
It may not work in this case (but i'm not sure)

2018-03-19 20:18 UTC, nsheremet commented
таки да

2018-03-19 20:38 UTC, nsheremet commented
только так выйдет `random(get_salt_size(@kdf))`

2018-03-20 11:36 UTC, nsheremet commented
каюсь

2018-03-20 15:56 UTC, Ptico requested changes

2018-03-20 15:56 UTC, Ptico commented on spec/unit/crypto/rbnacl_spec.rb
> +    context 'kedf options :argon2' do
kEdf

2018-03-20 15:56 UTC, Ptico commented on spec/unit/crypto/rbnacl_spec.rb
> +      let(:options) { Hash.new }
Укажи тут scrypt явно, лучше добавить тест для дефолтного поведения и тест когда такого kdf нет

2018-03-20 15:56 UTC, Ptico commented on spec/unit/crypto/rbnacl_spec.rb
> +      let(:length)  { 8 }
тут лучше рандомное значение от 1 до 100

2018-03-21 14:59 UTC, Ptico approved these changes

2018-03-21 15:00 UTC, merged